name: Windows build for Zed

on:
  push:
    tags:
      # Zed is soon to become ready on windows. msys2 already provides a package for it.
      # Keeping to bellow line for documentation only
      # - "weekly-release-[0-9]+"
      - "manual-release-zed-[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest

    steps:
    - name: Enable Long Paths in Windows
      run: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        git config --system core.longpaths true
      shell: pwsh

    - name: Set core count
      run: |
        $cores = (Get-CimInstance -ClassName Win32_ComputerSystem).NumberOfLogicalProcessors
        echo "CPU_CORES=$cores" >> $env:GITHUB_ENV

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Clone zed if folder doesn't exist
      run: git clone https://github.com/zed-industries/zed.git

    - name: Build Zed
      run: |
        cd zed
        cargo build --release --jobs $env:CPU_CORES --verbose
      env:
        CARGO_BUILD_JOBS: ${{ env.CPU_CORES }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./zed/target/release/zed.exe
        tag: ${{ github.ref_name }}
        overwrite: true
