name: Windows build for Zed

on:
  push:
    tags:
      - "zed-[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest

    steps:
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache Zed folder
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./zed/
          key: ${{ runner.os }}-zed

      - name: Clone zed if folder doesn't exist
        if: ${{ hashFiles('zed/') == '' }}
        run: git clone https://github.com/zed-industries/zed.git

      - name: Update repo if exists
        if: ${{ hashFiles('zed/') != '' }}
        run: |
          cd zed
          ls
          git pull

      - name: Build Zed
        run: |
          ls
          cd zed
          ls
          cargo build --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./zed/target/release/zed.exe
          tag: ${{ github.ref_name }}
          overwrite: true
