name: Windows build for Zed

on:
  push:
    tags:
      - "zed-[0-9]+"
    # branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: |
          git clone https://github.com/zed-industries/zed.git
          cd zed
          cargo run --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-bin
          path: zed/target/release/zed.exe

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zed/target/release/zed.exe
          tag: ${{ github.ref_name }}
          overwrite: true
