name: React to Release
on:
  push:
    tags:
      - "daily-release-[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check ref
        run: echo ${{ github.ref }}
